//
//  NewsDetailRouter.swift
//  LatestNews
//
//  Created by avanees on 26/07/2020.
//  Copyright (c) 2020 ave. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NewsDetailRouter: BaseRouter {

    // MARK: - Module setup -

    init(newsItem: NewsItem) {
        let moduleViewController = NewsDetailViewController()
        super.init(viewController: moduleViewController)
        
        let presenter = NewsDetailPresenter(view: moduleViewController, router: self,
                                            newsItem: newsItem)
        moduleViewController.presenter = presenter
    }
}

// MARK: - NewsDetailRouterInterface -

extension NewsDetailRouter: NewsDetailRouterInterface {
    func navigate(to option: NewsDetailNavigationOption) {
        switch option {
        case .showOriginalNewsItem(let newsItem): showOriginalNewsItem(newsItem)
        }
    }
        
    func showOriginalNewsItem(_ newsItem: NewsItem) {
        showSafariServicesViewWithUrl(newsItem.url)
    }
}
