//
//  NewsDetailPresenter.swift
//  LatestNews
//
//  Created by avanees on 26/07/2020.
//  Copyright (c) 2020 ave. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class NewsDetailPresenter {

    // MARK: - Private properties -

    private weak var view: NewsDetailViewInterface?
    private let router: NewsDetailRouterInterface
    private let newsItem: NewsItem

    // MARK: - Lifecycle -

    init(view: NewsDetailViewInterface, router: NewsDetailRouterInterface, newsItem: NewsItem) {
        self.view = view
        self.router = router
        self.newsItem = newsItem
    }
}

// MARK: - NewsDetailPresenterInterface -

extension NewsDetailPresenter: NewsDetailPresenterInterface {
    
    func viewDidLoad() {
        view?.update(with: getNewsItemViewModel())
    }
    
    private func getNewsItemViewModel() -> NewsDetailPresentable {
        let publishingDate = newsItem.publishedAt.toDate(format: .newsApiDateAndTimeFormat)
        let readablePublishingDate = publishingDate?.toString(format: .readableDateAndTimeFormat) ?? ""
        return NewsDetailViewModel(imageUrl: newsItem.urlToImage,
                                   title: newsItem.title,
                                   author: newsItem.author,
                                   publishingDate: readablePublishingDate,
                                   description: newsItem.description,
                                   content: newsItem.content)
    }
    
    func showOriginalNewsItem() {
        router.navigate(to: .showOriginalNewsItem(newsItem))
    }
}
