//
//  NewsListInteractor.swift
//  LatestNews
//
//  Created by avanees on 23/07/2020.
//  Copyright (c) 2020 ave. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Promises

final class NewsListInteractor {
    
    // MARK: - Public properties -
    
    weak var delegate: NewsListInteractorDelegate?
    
    // MARK: - Private properties -
    
    private let newsClient: NewsApiClientInterface

    init(newsClient: NewsApiClientInterface = NewsApiClient()) {
        self.newsClient = newsClient
    }
}

// MARK: - NewsListInteractorInterface -

extension NewsListInteractor: NewsListInteractorInterface {
    
    func fetchTopHeadlines() {
        newsClient.fetchTopHeadlines().then { headlinesResponse in
            guard let headlines = headlinesResponse.articles else { return }
            self.delegate?.interactor(self, didFetchTopHeadlines: headlines)
        }.catch { error in
            self.delegate?.interactor(self, failedRetrievingTopHeadlines: error)
        }
    }
}
